# Site settings
title: Loominate
subtitle: try not to fool yourself
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://loominate.net"  # the base hostname & protocol for your site
twitter_username: my_kl
github_username:  michaelgwelch

# Build settings
markdown: kramdown
kramdown:
  input: GFM

excerpt_separator: "<!--more-->"

theme: jekyll-theme-minimal
